// I download the gsheet as .csv an then went to https://csvjson.com/csv2json to transform between types.
// I added manually:     * canvasScale - translationFromCenter
// I separate the last 5 elements (target data) as a new trial

CDT_stimuli = [
  {
    trialnum: 1,
    condit: "same",
    stimamt: 4,
    upper_left_x: 0.14 * canvasScale - translationFromCenter,
    upper_left_y: 0.14 * canvasScale - translationFromCenter,
    color: "orange",
    presented: 1,
    upper_left_x2: 0.14 * canvasScale - translationFromCenter,
    upper_left_y2: -0.41 * canvasScale - translationFromCenter,
    color2: "blue",
    presented2: 1,
    upper_left_x3: -0.14 * canvasScale - translationFromCenter,
    upper_left_y3: -0.27 * canvasScale - translationFromCenter,
    color3: "white",
    presented3: 1,
    upper_left_x4: -0.41 * canvasScale - translationFromCenter,
    upper_left_y4: 0.14 * canvasScale - translationFromCenter,
    color4: "red",
    presented4: 1,
    upper_left_x5: 0.14 * canvasScale - translationFromCenter,
    upper_left_y5: 0.41 * canvasScale - translationFromCenter,
    color5: "black",
    presented5: 0,
    upper_left_x6: 0.27 * canvasScale - translationFromCenter,
    upper_left_y6: -0.27 * canvasScale - translationFromCenter,
    color6: "green",
    presented6: 0,
    upper_left_x7: -0.41 * canvasScale - translationFromCenter,
    upper_left_y7: -0.27 * canvasScale - translationFromCenter,
    color7: "magenta",
    presented7: 0,
    upper_left_x8: -0.41 * canvasScale - translationFromCenter,
    upper_left_y8: 0.41 * canvasScale - translationFromCenter,
    color8: "yellow",
    presented8: 0,
  },
  {
    upper_left_target_x: -0.14 * canvasScale - translationFromCenter,
    upper_left_target_y: 0.41 * canvasScale - translationFromCenter,
    presented_target: 1,
    color_target: "blue",
    corr_ans: "a",
  },
  {
    trialnum: 2,
    condit: "different",
    stimamt: 4,
    upper_left_x: 0.14 * canvasScale - translationFromCenter,
    upper_left_y: 0.41 * canvasScale - translationFromCenter,
    color: "black",
    presented: 1,
    upper_left_x2: 0.14 * canvasScale - translationFromCenter,
    upper_left_y2: -0.41 * canvasScale - translationFromCenter,
    color2: "green",
    presented2: 1,
    upper_left_x3: -0.41 * canvasScale - translationFromCenter,
    upper_left_y3: -0.27 * canvasScale - translationFromCenter,
    color3: "orange",
    presented3: 1,
    upper_left_x4: -0.27 * canvasScale - translationFromCenter,
    upper_left_y4: 0.41 * canvasScale - translationFromCenter,
    color4: "magenta",
    presented4: 1,
    upper_left_x5: 0.14 * canvasScale - translationFromCenter,
    upper_left_y5: 0.27 * canvasScale - translationFromCenter,
    color5: "red",
    presented5: 0,
    upper_left_x6: 0.41 * canvasScale - translationFromCenter,
    upper_left_y6: -0.27 * canvasScale - translationFromCenter,
    color6: "white",
    presented6: 0,
    upper_left_x7: -0.27 * canvasScale - translationFromCenter,
    upper_left_y7: -0.41 * canvasScale - translationFromCenter,
    color7: "yellow",
    presented7: 0,
    upper_left_x8: -0.27 * canvasScale - translationFromCenter,
    upper_left_y8: 0.27 * canvasScale - translationFromCenter,
    color8: "blue",
    presented8: 0,
  },
  {
    upper_left_target_x: -0.27 * canvasScale - translationFromCenter,
    upper_left_target_y: 0.41 * canvasScale - translationFromCenter,
    presented_target: 1,
    color_target: "white",
    corr_ans: "l",
  },
  {
    trialnum: 3,
    condit: "same",
    stimamt: 8,
    upper_left_x: 0.27 * canvasScale - translationFromCenter,
    upper_left_y: 0.41 * canvasScale - translationFromCenter,
    color: "yellow",
    presented: 1,
    upper_left_x2: 0.14 * canvasScale - translationFromCenter,
    upper_left_y2: -0.41 * canvasScale - translationFromCenter,
    color2: "white",
    presented2: 1,
    upper_left_x3: -0.14 * canvasScale - translationFromCenter,
    upper_left_y3: -0.27 * canvasScale - translationFromCenter,
    color3: "blue",
    presented3: 1,
    upper_left_x4: -0.14 * canvasScale - translationFromCenter,
    upper_left_y4: 0.27 * canvasScale - translationFromCenter,
    color4: "green",
    presented4: 1,
    upper_left_x5: 0.14 * canvasScale - translationFromCenter,
    upper_left_y5: 0.14 * canvasScale - translationFromCenter,
    color5: "red",
    presented5: 1,
    upper_left_x6: 0.27 * canvasScale - translationFromCenter,
    upper_left_y6: -0.27 * canvasScale - translationFromCenter,
    color6: "black",
    presented6: 1,
    upper_left_x7: -0.27 * canvasScale - translationFromCenter,
    upper_left_y7: -0.27 * canvasScale - translationFromCenter,
    color7: "magenta",
    presented7: 1,
    upper_left_x8: -0.27 * canvasScale - translationFromCenter,
    upper_left_y8: 0.14 * canvasScale - translationFromCenter,
    color8: "orange",
    presented8: 1,
  },
  {
    upper_left_target_x: -0.14 * canvasScale - translationFromCenter,
    upper_left_target_y: 0.27 * canvasScale - translationFromCenter,
    presented_target: 1,
    color_target: "green",
    corr_ans: "a",
  },
  {
    trialnum: 4,
    condit: "different",
    stimamt: 8,
    upper_left_x: 0.14 * canvasScale - translationFromCenter,
    upper_left_y: 0.41 * canvasScale - translationFromCenter,
    color: "green",
    presented: 1,
    upper_left_x2: 0.27 * canvasScale - translationFromCenter,
    upper_left_y2: -0.14 * canvasScale - translationFromCenter,
    color2: "red",
    presented2: 1,
    upper_left_x3: -0.27 * canvasScale - translationFromCenter,
    upper_left_y3: -0.14 * canvasScale - translationFromCenter,
    color3: "black",
    presented3: 1,
    upper_left_x4: -0.14 * canvasScale - translationFromCenter,
    upper_left_y4: 0.41 * canvasScale - translationFromCenter,
    color4: "orange",
    presented4: 1,
    upper_left_x5: 0.41 * canvasScale - translationFromCenter,
    upper_left_y5: 0.27 * canvasScale - translationFromCenter,
    color5: "blue",
    presented5: 1,
    upper_left_x6: 0.41 * canvasScale - translationFromCenter,
    upper_left_y6: -0.27 * canvasScale - translationFromCenter,
    color6: "magenta",
    presented6: 1,
    upper_left_x7: -0.14 * canvasScale - translationFromCenter,
    upper_left_y7: -0.14 * canvasScale - translationFromCenter,
    color7: "white",
    presented7: 1,
    upper_left_x8: -0.27 * canvasScale - translationFromCenter,
    upper_left_y8: 0.14 * canvasScale - translationFromCenter,
    color8: "yellow",
    presented8: 1,
  },
  {
    upper_left_target_x: 0.27 * canvasScale - translationFromCenter,
    upper_left_target_y: -0.14 * canvasScale - translationFromCenter,
    presented_target: 1,
    color_target: "white",
    corr_ans: "l",
  },
];
